//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoKioski
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BancoKioskiEntities : DbContext
    {
        public BancoKioskiEntities()
            : base("name=BancoKioskiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cartao> cartaos { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<funcionario> funcionarios { get; set; }
        public virtual DbSet<mesa> mesas { get; set; }
        public virtual DbSet<pagamento> pagamentoes { get; set; }
        public virtual DbSet<pedido> pedidoes { get; set; }
        public virtual DbSet<pedidoproduto> pedidoprodutoes { get; set; }
        public virtual DbSet<produto> produtoes { get; set; }
    }
}
