//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoKioski
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagamento
    {
        public int id { get; set; }
        public byte[] data { get; set; }
        public Nullable<float> desconto { get; set; }
        public int id_pedido { get; set; }
        public float valor { get; set; }
    
        public virtual pedido pedido { get; set; }
    }
}
