//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoKioski
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public pedido()
        {
            this.pagamentoes = new HashSet<pagamento>();
            this.pedidoprodutoes = new HashSet<pedidoproduto>();
        }
    
        public int id { get; set; }
        public byte[] data { get; set; }
        public int id_cartao { get; set; }
        public int id_cliente { get; set; }
        public int id_mesa { get; set; }
        public int id_funcionario { get; set; }
        public string status { get; set; }
        public Nullable<float> valorTotal { get; set; }
    
        public virtual cartao cartao { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual mesa mesa { get; set; }
        public virtual ICollection<pagamento> pagamentoes { get; set; }
        public virtual ICollection<pedidoproduto> pedidoprodutoes { get; set; }
    }
}
